#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: gg <branch_name> <commit_message>"
	echo ""
    echo "Example: gg feature/changing_purchase_button_color \"Making the purchase button red.\""
    exit 1
fi

if git 2>&1 | grep -q "command not found"; then
  echo "fatal: command not found: git"
  exit 1
fi

if git status 2>&1 | grep -q "not a git repository"; then
  echo "fatal: not a git repository (or any of the parent directories): .git"
  exit 1
fi

if git status 2>&1 | grep -q "nothing to commit"; then
  echo "no changes added to commit (use "git add")"
  exit 1
fi

if git status 2>&1 | grep -q "no changes added to commit"; then
  echo "no changes added to commit (use "git add")"
  exit 1
fi

CURRENT_BRANCH="$(git symbolic-ref HEAD 2>&1 | cut -d/ -f3-)"

if git checkout -b $1 2>&1 | grep -q "already exists"; then
  echo "fatal: A branch named '$1' already exists."
  exit 1
fi

# Currently GG supports 4 platforms: Github, Gitlab, Azure, and Bitbucket.
# They all use different paths for creating their merge requests.
# For Github it should match "pull/new"
# For Gitlab it should match "merge_requests/new"
# For Azure it should match "pullrequest"
# For Bitbucket it should match "pull-requests/new"

git commit -m "$2"
URL="$(git push origin HEAD 2>&1 | grep -Eo 'http.*((pull/new)|(merge_requests/new)|(pullrequest)|(pull-requests/new)).*')"
open $URL
git checkout $CURRENT_BRANCH
